### ISSUE TITLE
English HTML

### ISSUE THREAD

**Issue by pacwoodson** [bombmanual/bombmanual.github.io#43]
Hi, 

I would like to translate it to french, do you know where I can find the english html version to start on ?

Thanks

**Comment by brugnara** [comment]
@pakokrew hi. Thank you for your interest in this project.

I suggest you to use the original HTML you can find on the official site: `http://www.bombmanual.com/manual/1/html/index.html`

Contributing is easy. Just create a folder with the `index.html` translated alone and open new pull request.

Thank you.
