### ISSUE TITLE
German printing is broken

### ISSUE THREAD

**Issue by NoFr1ends** [bombmanual/bombmanual.github.io#69]
The table for the complex cables is breaking the printing for the German version.
As a result the table for the instructions (14) is moved inside the Labyrinth page (15)

**Comment by Vankog** [comment]
@Mave213, could you please check your latest compilation of #68?

**Comment by pk-dot** [comment]
I fixed it and created a pull request. 
https://github.com/pascal-klaeres/bombmanual.github.io

**Comment by brugnara** [comment]
#71
