### ISSUE TITLE
unify all repos into this one

### ISSUE THREAD

**Issue by brugnara** [bombmanual/bombmanual.github.io#7]
I think unify all repos into this one can be a good choice to speed up the updates made to the various languages.

What do you think guys?

@jaramir @L3viathan @BrightSoul @Rouzax @DmitryScaletta

**Comment by jaramir** [comment]
👍 for me.

Will we keep all discussions in English?

**Comment by brugnara** [comment]
@jaramir We can speak the language the issue refers to, IMHO.

**Comment by L3viathan** [comment]
Sure, I'm fine with that.

**Comment by Rouzax** [comment]
Fine with me :smile:

**Comment by L3viathan** [comment]
Alright, why not.

**Comment by brugnara** [comment]
done!
