### ISSUE TITLE
Printing issue with german version

### ISSUE THREAD

**Issue by redxeagle** [bombmanual/bombmanual.github.io#9]
Page 11 flow over to the Page 12.
same for page 14 to page 15

Tested in Chrome and Edge printing view.
Tested with two different printer ...

![image](https://cloud.githubusercontent.com/assets/727418/21311935/096d73aa-c5ea-11e6-947f-1f731196310b.png)

**Comment by brugnara** [comment]
Thank you @redxeagle for reporting this. 

@L3viathan

**Comment by L3viathan** [comment]
Seems fixed after the pull request by @chdudek.

I checked with printing preview on Safari.

**Comment by brugnara** [comment]
can you please confirm this is fixed, @redxeagle ?

Thank you @L3viathan for your check!

**Comment by redxeagle** [comment]
Checked out both repository. You should accept the pull request from @chdudek
His forked repository looks good now.

**Comment by brugnara** [comment]
I'll check. Thank you.

**Comment by DmitryScaletta** [comment]
![](http://i.imgur.com/wNzBsyT.png)
All translations have this printing issue in the latest Chrome.
So [here](https://github.com/DmitryScaletta/Bomb-Defusal-Manual-rus/commit/b4277d055a7008d2e948379a195b1716179f46c0) is possible solution.
